#!/usr/bin/env python3

import sys
import os

from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import colored


def main():
	# ensure that a screen name was given
    if len(sys.argv)!=2:
        sys.exit("Usage: ./tweets screenname")

	# recognize the screen name from the user's input
    screen_name = sys.argv[1]

	# absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

	# get the user's most recent 50 tweets
    tweets = get_user_timeline(screen_name, 50)

	# if nothing is returned from tweets, then prompt the user for another screen name
    if tweets == None:
        sys.exit("Please try another screen name. User is private or doesn't exist.")

	 # otherwise the function will return individual tweet in the list tweets.
    else:
	     # iterate over the list of tweets
        for tweet in tweets:
			# analyze the tweet to get it’s score
            score = analyzer.analyze(tweet)
			# determine if the score is positive, negative or neutral.
			# print out the score and the tweet
            if score > 0.0:
                print(colored("{} {}" .format(score, tweet), "green"))
            elif score < 0.0:
                print(colored("{} {}" .format(score, tweet), "red"))
            else:
                print(colored("{} {}" .format(score, tweet), "yellow"))

if __name__ == "__main__":
	main()
